import React from 'react';
import { Sparkles, CheckCircle2, Tag, Compass, X, Copy, Check } from 'lucide-react';
import type { ReflectionSummary } from '../types';

interface SummaryCardProps {
  summary: ReflectionSummary;
  onClose?: () => void;
}

export const SummaryCard: React.FC<SummaryCardProps> = ({ summary, onClose }) => {
  const [copied, setCopied] = React.useState(false);

  const handleCopy = () => {
    const text = `## AI Reflection Summary\n${summary.summary}\n\n### Mood Tone\n${summary.moodTone}\n\n### Key Takeaways\n${summary.keyTakeaways.map((t) => `- ${t}`).join('\n')}\n\n### Core Themes\n${summary.coreThemes.join(', ')}\n\n### Actionable Prompts\n${summary.actionablePrompts.map((p) => `- ${p}`).join('\n')}`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="rounded-2xl bg-[#161618] border border-indigo-500/30 p-5 sm:p-6 shadow-xl text-[#E0E0E0] relative overflow-hidden">
      {/* Glow accent */}
      <div className="absolute -top-12 -right-12 w-32 h-32 bg-indigo-500/10 rounded-full blur-2xl pointer-events-none" />

      {/* Header */}
      <div className="flex items-center justify-between pb-4 border-b border-[#2A2A2E]">
        <div className="flex items-center space-x-2.5">
          <div className="w-8 h-8 rounded-lg bg-indigo-500/20 border border-indigo-500/30 flex items-center justify-center text-indigo-400">
            <Sparkles className="w-4 h-4" />
          </div>
          <div>
            <h3 className="font-serif font-bold text-sm text-[#E0E0E0]">Cognitive Synthesis & Summary</h3>
            <p className="text-[11px] text-[#9CA3AF]">Generated by Gemini 3.6 Flash</p>
          </div>
        </div>

        <div className="flex items-center space-x-2">
          <button
            onClick={handleCopy}
            className="inline-flex items-center px-2.5 py-1 text-xs rounded-lg bg-[#1A1A1D] hover:bg-[#222226] border border-[#2A2A2E] text-[#E0E0E0] transition-colors cursor-pointer"
            title="Copy summary"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400 mr-1" /> : <Copy className="w-3.5 h-3.5 mr-1 text-[#9CA3AF]" />}
            {copied ? 'Copied' : 'Copy'}
          </button>
          {onClose && (
            <button
              onClick={onClose}
              className="p-1 rounded-lg text-[#6B7280] hover:text-[#E0E0E0] hover:bg-[#1A1A1D] transition-colors cursor-pointer"
              aria-label="Close summary"
            >
              <X className="w-4 h-4" />
            </button>
          )}
        </div>
      </div>

      {/* Summary Narrative */}
      <div className="mt-4">
        <h4 className="text-xs font-semibold uppercase tracking-wider text-indigo-400 mb-1.5 font-sans">
          Executive Reflection
        </h4>
        <p className="text-xs sm:text-sm text-[#E0E0E0] leading-relaxed bg-[#1A1A1D] p-3.5 rounded-xl border border-[#2A2A2E]">
          {summary.summary}
        </p>
      </div>

      {/* Mood & Themes */}
      <div className="mt-4 grid grid-cols-1 sm:grid-cols-2 gap-3">
        <div className="bg-[#1A1A1D] p-3 rounded-xl border border-[#2A2A2E]">
          <span className="text-[11px] font-semibold text-[#9CA3AF] uppercase tracking-wider block mb-1">
            Mood & Emotional Tone
          </span>
          <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-indigo-500/15 text-indigo-300 border border-indigo-500/30">
            {summary.moodTone}
          </span>
        </div>

        <div className="bg-[#1A1A1D] p-3 rounded-xl border border-[#2A2A2E]">
          <span className="text-[11px] font-semibold text-[#9CA3AF] uppercase tracking-wider block mb-1">
            Thematic Clusters
          </span>
          <div className="flex flex-wrap gap-1.5">
            {summary.coreThemes && summary.coreThemes.length > 0 ? (
              summary.coreThemes.map((theme, i) => (
                <span
                  key={i}
                  className="inline-flex items-center text-[10px] bg-[#161618] text-[#A0A0A0] px-2 py-0.5 rounded border border-[#2A2A2E]"
                >
                  <Tag className="w-2.5 h-2.5 mr-1 text-[#6B7280]" />
                  {theme}
                </span>
              ))
            ) : (
              <span className="text-xs text-[#6B7280]">No themes detected</span>
            )}
          </div>
        </div>
      </div>

      {/* Key Takeaways */}
      {summary.keyTakeaways && summary.keyTakeaways.length > 0 && (
        <div className="mt-4">
          <h4 className="text-xs font-semibold uppercase tracking-wider text-indigo-400 mb-2 font-sans">
            Key Insights & Realizations
          </h4>
          <ul className="space-y-1.5">
            {summary.keyTakeaways.map((item, idx) => (
              <li key={idx} className="flex items-start text-xs text-[#E0E0E0]">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400 mr-2 shrink-0 mt-0.5" />
                <span className="leading-normal">{item}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Actionable Forward Prompts */}
      {summary.actionablePrompts && summary.actionablePrompts.length > 0 && (
        <div className="mt-4 pt-3 border-t border-[#2A2A2E]">
          <h4 className="text-xs font-semibold uppercase tracking-wider text-indigo-400 mb-2 font-sans flex items-center">
            <Compass className="w-3.5 h-3.5 mr-1.5" />
            Actionable Inquiries
          </h4>
          <div className="space-y-1.5">
            {summary.actionablePrompts.map((prompt, idx) => (
              <div
                key={idx}
                className="text-xs text-[#E0E0E0] bg-indigo-950/25 border border-indigo-500/25 p-2.5 rounded-lg"
              >
                {prompt}
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};
